사서의 로테이션 신청기록을 반환하는 API 추가
Together42/backend pull request #173
Opened 2023-03-29 11:27 UTC by sideseal

https://github.com/Together42/backend/issues/171

`GET` `/api/rotation/atteend?intraId=[intraId]&month=[month]&year=[year]`
* intraId는 필수 입력 사항입니다.
* month와 year는 옵션 사항입니다.
  * month와 year을 제외하고 쿼리를 전송할 시, 해당 사서의 모든 로테이션 참석 기록이 반환됩니다. 
  * month만 입력 시, 모든 년도에 대해 해당 월의 참석 기록이, year만 입력 시, 모든 월에 대해 해당 년도의 참석 기록이 반환됩니다.
* 음.... 만들고 나서 유저 '본인'의 요청인 점을 확인했는데... 혹시 해당 API도 괜찮을지, 혹은 변경이 필요할지 궁금합니다 흑...

2023-03-29 14:10 UTC, jhj9109 requested changes
코드를 약간 손봤습니다.
우선 올바른 기능 구현이 최우선이지만, 코드가 간결하면 그 올바름을 파악하기 쉬워집니다.
한번 구현 해놓으면 다시 손대기가 은근히 쉽지 않아서, 먼저 기능 구현 후에 약간의 시간을 투자해서
간결하게 줄일 수 없을지 고민해보고 가능하면 리팩토링해봐도 좋습니다.

API모양은 모두의 attend 기록을 조회할 일은 아직 없어서, 우선 특정 한명에 대한 attend 요청을 생각해서
처음에 제안한 GET /api/rotation/attend 모양이였습니다. (누군지는 토큰을 통해서)
지금처럼 모두 && 특정 한명을 조회하는 api라면 아래처럼도 가능할 거 같습니다.

GET /api/rotation/attend 모든 attend 조회
GET /api/rotation/attend/:intraId?month={옵셔널}&year={옵셔널} 특정 한명에 대한 조회

API 모양에 대해선 다른 백엔드분들의 의견을 더 들으시면 될거같습니다.

2023-03-30 06:46 UTC, sideseal commented on src/controller/rotation.controller.js
> +export async function getUserParticipation(req, res) {
정말 최고입니다... 저도 함수가 생각보다 너무 길고 지저분하다는 느낌이 들었는데, 이렇게 깔끔하게 작성된 코드를 보여주셔서 너무 감사하면서도 죄송하네요... 지저분하게 작성된 남의 코드를 읽는 일이 쉽지 않으셨을텐데, 밤 늦게 고생 많으셨습니다...

정규표현식으로 쿼리 값을 체크하는 방법이 있었군요... 다음에 꼭 한번 사용해봐야겠습니다. 그리고 앞으로 기능 구현이 급하지 않는 한, 깔끔하게 모두 작성하고 코드를 올리도록 해야겠어요. (시간나면 해야지 하면서도 말씀하신대로 손대기가 쉽지 않네요...)

위에 올려주신 코드로 변경하고 테스트해보니, 모두 잘 작동하여 올려주신 코드로 변경하고 다시 커밋했습니다. 
(다만 month, year의 인자가 정수가 아닌 문자열이 들어오는 경우, except 처리되지 않고 가장 하단으로 이동하게 되는데, 백엔드 API에서는 크게 신경쓰지 않아도 되겠죠...??)

그리고 지금처럼 쿼리스트링으로 특정(혹은 모두) 인물의 정보를 가져오도록 해도 괜찮을까요...?? 혹시 토큰을 통해 로그인한 유저의 정보를 받는 API가 필요하신 경우, 말씀해주시면 빠르게 수정하겠습니다!!

항상 현잔님께 많이 배웁니다... 훌륭한 코드 리뷰 다시 한 번 감사드립니다!!!

2023-03-31 10:12 UTC, jhj9109 commented on src/controller/rotation.controller.js
> +export async function getUserParticipation(req, res) {
(다만 month, year의 인자가 정수가 아닌 문자열이 들어오는 경우, except 처리되지 않고 가장 하단으로 이동하게 되는데, 백엔드 API에서는 크게 신경쓰지 않아도 되겠죠...??)
=> req.query에 담긴애들은 key - value구조로 기본적으로 value는 string이고 string에 맞추어 코딩했습니다. 쿼리파서등 라이브러리등을 사용할때, 편리하라고 key-value로 저장시 타입을 적절히 설정해주는것으로 압니다. 추가적으로 오히려 자료형이 Number일때 문제가 생길까 싶어 테스트 해보니 정규표현식.test(123)을 하면 123을 자동으로 string으로 변환후 사용하는거 같습니다.

그리고 지금처럼 쿼리스트링으로 특정(혹은 모두) 인물의 정보를 가져오도록 해도 괜찮을까요...?? 혹시 토큰을 통해 로그인한 유저의 정보를 받는 API가 필요하신 경우, 말씀해주시면 빠르게 수정하겠습니다!!
=> FE에서 토큰을 가지고 있을때 intraId도 기본적으로 가지고 있어서, 지금처럼 명시적으로 intraId를 요청 URL에 포함하는건 괜찮습니다. API모양에 대해선 백엔드쪽 누군가 의견이 있으면 반영해서 수정해도 좋을거 같고, 그게 아니면 지금 형태로도 충분히 사용가능하니까 굳이 수정하지 않는게 오히려 나을거 같습니다.

코드 간결하게 짜는것은 적절한 경험이 누적되면 자연스레 해결되는 부분이라, 적절한 경험을 위해 기능 구현후에 리팩토링도 해보셔라고 말씀드렸습니다. API 코드 짜는게 로직이 비슷비슷한게 많아서, <기능 구현하고 && 리팩토링>요 사이클 몇번 도시면 금방 익숙해지실겁니다. 요렇게 익숙해져야..... 이제 여기서 요청에 대한 유효성검증 코드들이 적절한 곳에 적절한 방식으로 끼워 넣는게 수월해지실겁니다. 화이팅입니다~🤟

2023-03-31 11:33 UTC, sideseal commented on src/controller/rotation.controller.js
> +export async function getUserParticipation(req, res) {
감사합니다!!! 그렇다면 API 작업 올리겠습니다 ㅎㅎ 현잔님 덕분에 많이 배웠어요. 말씀해주신 내용 잘 기억하고, 다음 기능 구현을 이어나가겠습니다. 도와주셔서 감사합니다!!! :smiley:

2023-03-31 12:47 UTC, sideseal commented on src/controller/rotation.controller.js
> +export async function getUserParticipation(req, res) {
헐... 인자로 바로 타입 체크하는게 너무 편해보이네요... 친바 타입스크립트 변환 작업도 해야하는데... 블랙홀 빨리 벌어놓고 날잡고 작성한 코드 손을 좀 봐야겠습니다 ㅎㅎ 좋은 라이브러리 소개해주셔서 감사해요!!!

2023-04-06 23:47 UTC, keinn51 approved these changes
이미 충분한 리뷰가 되었다고 판단되어 어프루브 남깁니다

2023-04-06 23:47 UTC, merged